---
- name: "Install Packages"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - wget
    - curl
    - nginx

- name: "Stat Web Service"
  service:
    name: "{{ hello_web.service }}"
    state: started
    enabled: yes

- name: "Copy Content"
  copy:
    src: "{{ role_path }}/files/index.html"
    dest: "{{ hello_web.docroot }}/index.html"
